import "./globals.css";
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import { cn } from './/lib/utils';

import Header from './/components/header'

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' }
  ]
}


export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={cn(
                'font-sans antialiased',
                GeistSans.variable,
                GeistMono.variable
            )}
        >
        <div className="flex flex-col min-h-screen">
            <Header/>
            <main className="flex flex-col flex-1 bg-muted/50">{children}</main>
        </div>
        </body>
        </html>
    );
}
